[package]
name = "datesapp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
axum-macros = "0.5.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8", features = [ "sqlite", "runtime-tokio" ] }
serde = "1.0.217"
bcrypt = "0.16"

